### ISSUE TITLE
Property 'ref' does not exist on type 'ReflectedTypeRef<RtTypeRef>

### ISSUE THREAD

**Issue by capaj** [rezonant/typescript-rtti#14]
```ts

import 'reflect-metadata'
import { reflect } from 'typescript-rtti'

interface IMyInterface {
  a: number
}

class A implements IMyInterface {
  constructor(readonly someValue: Number, private someOtherValue: string) {}
  a: number
}

class A2 implements IMyInterface {
  a: number
}

class B {
  private foo: A
  bar = 123
  async baz(param: A2): Promise<Array<A | null | undefined>> {
    return [this.foo]
  }
}

let bClass = reflect(B)

console.log(bClass.getMethod('baz').getParameter('param').type)

console.log(bClass.getMethod('baz').returnType.ref.p[0].p[0].t[0] === A) 
```

![image](https://user-images.githubusercontent.com/1305378/154793045-774289b4-a0c2-4b73-bc76-d1b9c5723e32.png)

This code runs fine, but the typing seems to think the `ref` getter does not exist.

Tested with 0.1.4

**Comment by rezonant** [comment]
The `ref` field is internal and shouldn't be used directly. You can't access it because it's effectively private. You should instead use the `is*()` discriminant functions to narrow the type of `returnType`, check the `kind` property and then cast, or use `as()` to do a type-checked cast. For instance, in your example above, you could do:

```typescript
console.log(reflect(A).getMethod('foo').returnType.as('generic').typeParameters[0].as('array').elementType.isClass(A));
```

The is() functions use type discriminants (ie `this is X` TS syntax) to auto-narrow the type...

![image](https://user-images.githubusercontent.com/409140/154793865-eaf99c57-1ac1-43cf-b0df-43f409b1b2b3.png)

The `kind` field also becomes narrowed:

![image](https://user-images.githubusercontent.com/409140/154793897-0d718935-67a7-484e-8e49-888b6014b736.png)

The possible kinds come from `ReflectedTypeRefKind`:

```typescript
export type ReflectedTypeRefKind = 'union' | 'intersection' | 'any' 
    | 'unknown' | 'tuple' | 'array' | 'class' | 'any' | 'unknown' | 'generic' | 'literal' | 'void' | 'interface';
```

There are many kinds of type reference:

![image](https://user-images.githubusercontent.com/409140/154793944-730d66cd-21b6-42cc-b3f3-afa2a7794f84.png)

**Comment by rezonant** [comment]
Note that depending on any of the RtTypeRef or other parts of it is not a good idea because the metadata format may change in the future. Also the reflect() API works both for rtti and emitDecoratorMetadata annotations-- so its a unified API. Also I intend to implement any other metadata format that crops up under the reflect() api, so this should future proof libraries that want to consume the metadata

**Comment by capaj** [comment]
Thanks for clarification. Problem is I don't have a reference to A.
In decapi A is a user object, which is not known ahead of time. So I definitely need a way to get a reference to A without an explicit `isClass(A)` check. Is there no public method API to do this ATM?

**Comment by rezonant** [comment]
Use `is('class').class`

**Comment by capaj** [comment]
thanks, that clears it up.
